### PR TITLE
Support for pydantic v1 & v2

### LINKED ISSUE #291: pydantic > 2.1.0 is too restrictive
## Restrictive Dependency

pydantic's minimum version was bumped from 2.1.0, which was released less than 3 weeks ago.
https://github.com/supabase-community/gotrue-py/blob/c2ed950516e4b9bee6eb8f066969049b9a361a28/pyproject.toml#L20

pydantic is a common dependency, particularly among API building libraries and this makes gotrue-py/supabase-py incompatible with those libs

For example, we are currently incompatible with FastAPI and LangChain

### PR DESCRIPTION
**Pull request by olirice**
## What kind of change does this PR introduce?
Re-adds support for pydantic v1 via a few compatibility functions in `helpers.py`

The change is mostly mechanical and mirrors the update that transitioned from pydantic  v1 to v2 https://github.com/supabase-community/gotrue-py/pull/286

---

resolves #291
ref https://github.com/supabase-community/supabase-py/issues/517

### CODE REVIEW

**Comment by olirice** [comment]
The tests now run in CI once with pydantic v2 and again with v1.10.12 but the coverage is only 37% so I'd appreciate a review! or if anyone has an extensive existing project they can test this out against that'd be great too

tag @yuvanist (for review) if you have a few minutes

**Comment by sjhansen3** [comment]
+1 on getting this PR in. I'm seeing that a big draw for the Supabase Python client is its use in AI projects. That pydantic version restriction is causing some hiccups. It's making things incompatible with:

langchain
chroma
(and I'm guessing there are a few others)
For me, the essence of the Python client is to mesh Supabase into our Python workflows, especially in AI territory. I know there's a broad world of Python use cases, but this feels like a core one.

**Comment by yuvanist** [comment]
LGTM. @J0 please merge this.

**Comment by J0** [comment]
@yuvanist sure, thanks for taking the time to review! Let me test it tomorrow alongside the `GoTrue-py` and I'll merge thereafter. 

Hey @sjhansen3,

Great to see you again! It's been a while - cool to hear that you're using the client. It's community maintained so there are a lot of rough edges but let us know if there's anything we can help you with. Would recommend taking a look at the [vecs library](https://github.com/supabase/vecs) that @olirice  has written - it's official and in my opinion better suited for working with embeddings.

**Pull request merged**
