### PR TITLE
feat: add pre-commit hook and action for conventional commit and semantic release

### LINKED ISSUE #30: docs: add semantic release github action
Maybe these links can help:

- https://mestrak.com/blog/semantic-release-with-python-poetry-github-actions-20nn
- https://github.com/bjoluc/semantic-release-config-poetry

### LINKED ISSUE #31: chore: add pre-commit hook for force conventional commits style

### PR DESCRIPTION
**Pull request by leynier**
Resolve #30 
Resolve #31

### CODE REVIEW

**Review by dreinon — APPROVED** [review]

**Review by J0 — APPROVED** [review]
Thanks for the PR! It looks good to me. While I have access to the PyPI Repository, it seems like we need to get approval to add secrets to the Github repository. Requesting for that now.

**Comment by dreinon** [comment]
tests are failing  and I don't really know why, could you please take a look @leynier? Thanks!

**Comment by leynier** [comment]
> tests are failing  and I don't really know why, could you please take a look @leynier? Thanks!

Yes, I will.

**Comment by leynier** [comment]
@dreinon already tests running fine

**Comment by dreinon** [comment]
@leynier codecov/patch is failing, is this meaningful?

**Comment by dreinon** [comment]
@leynier tests failing due to connection errors

**Comment by leynier** [comment]
Tests are failing by this https://github.com/supabase/gotrue-js/issues/188#issuecomment-985206297

**Pull request merged**
