### PR TITLE
Change `.update` method to also allow dictionaries

### PR DESCRIPTION
**Pull request by odiseo0**
This change is for providing an api equal to the supabase-js from the docs of Supabase [here](https://supabase.com/docs/reference/javascript/auth-update#notes)

### CODE REVIEW

**Comment by odiseo0** [comment]
Mmmmmm, I thought this was for Python higher than 3.7

**Comment by leynier** [comment]
You can try some like this maybe

```python
import sys

if sys.version_info >= (3, 8):
    from typing import TypedDict
else:
    from typing_extensions import TypedDict
```

**Comment by odiseo0** [comment]
Yes, will do later, thank you

**Comment by leynier** [comment]
> Yes, will do later, thank you

Thank to you for the contribution 🤜🤛

**Comment by odiseo0** [comment]
Why does it fail?

**Comment by leynier** [comment]
> Why does it fail?

Because the format of the code is not correct, you can run `make tests_pre_commit` to check that.

**Pull request closed without merging**
